# Basic Site Settings
locale                   : "en-US"
title                    : "Dilara Vefa Ayyildiz"
title_separator          : "-"
name                     : &name "Dilara Vefa Ayyildiz"
description              : &description "Computer Vision Engineer and Data Scientist"
url                      : https://academicpages.github.io 
baseurl                  : "" 
repository               : "academicpages/academicpages.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Dilara Vefa Ayyildiz"
  pronouns         : "she/her"
  bio              : "Computer Vision Engineer and Data Scientist specializing in AI and autonomous driving."
  location         : "Florida / USA"
  employer         : "Florida Polytechnic University"
  email            : "vefaayyildiz@gmail.com"

# Site Settings
teaser                   : 
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

# Analytics
analytics:
  provider               :  "false"

# Collections for the new sections
collections:
  education:
    output: true
    permalink: /:collection/:path/
  experience:
    output: true
    permalink: /:collection/:path/
  research_projects:
    output: true
    permalink: /:collection/:path/
  teaching_tutoring:
    output: true
    permalink: /:collection/:path/
  conferences_events:
    output: true
    permalink: /:collection/:path/
  leaderships:
    output: true
    permalink: /:collection/:path/
  activities:
    output: true
    permalink: /:collection/:path/

# Defaults for new sections
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  # _education
  - scope:
      path: ""
      type: education
    values:
      layout: single
      author_profile: true
  # _experience
  - scope:
      path: ""
      type: experience
    values:
      layout: single
      author_profile: true
  # _research_projects
  - scope:
      path: ""
      type: research_projects
    values:
      layout: single
      author_profile: true
  # _teaching_tutoring
  - scope:
      path: ""
      type: teaching_tutoring
    values:
      layout: single
      author_profile: true
  # _conferences_events
  - scope:
      path: ""
      type: conferences_events
    values:
      layout: single
      author_profile: true
  # _leaderships
  - scope:
      path: ""
      type: leaderships
    values:
      layout: single
      author_profile: true
  # _activities
  - scope:
      path: ""
      type: activities
    values:
      layout: single
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
